from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sa.String(320), nullable=False), sa.Column("password_hash", sa.Text(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table("memories", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("layer", sa.String(32), nullable=False), sa.Column("memory_type", sa.String(32), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("importance", sa.Float(), nullable=False, server_default="0.5"), sa.Column("confidence", sa.Float(), nullable=False, server_default="0.8"), sa.Column("expires_at", sa.DateTime()), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_index("ix_memories_user_id", "memories", ["user_id"])
    op.create_index("ix_memories_layer", "memories", ["layer"])
    op.create_table("health_records", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("source", sa.String(64), nullable=False), sa.Column("image_type", sa.String(32)), sa.Column("summary", sa.Text(), nullable=False), sa.Column("risk_level", sa.String(16), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_health_records_user_id", "health_records", ["user_id"])
    op.create_table("health_metrics", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("record_id", sa.Integer(), sa.ForeignKey("health_records.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(64), nullable=False), sa.Column("value", sa.String(128), nullable=False), sa.Column("unit", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_health_metrics_record_id", "health_metrics", ["record_id"])
    op.create_table("health_alerts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("record_id", sa.Integer(), sa.ForeignKey("health_records.id", ondelete="SET NULL")), sa.Column("severity", sa.String(16), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("acknowledged", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_health_alerts_user_id", "health_alerts", ["user_id"])
    op.create_table("products", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("product_id", sa.String(64), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("price_minor", sa.Integer(), nullable=False), sa.Column("currency", sa.String(8), nullable=False), sa.Column("interval", sa.String(16), nullable=False), sa.Column("stripe_price_id", sa.String(128), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index("ix_products_product_id", "products", ["product_id"], unique=True)
    op.create_table("orders", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("order_no", sa.String(64), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("product_id", sa.String(64), nullable=False), sa.Column("amount_minor", sa.Integer(), nullable=False), sa.Column("currency", sa.String(8), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_orders_order_no", "orders", ["order_no"], unique=True); op.create_index("ix_orders_user_id", "orders", ["user_id"])
    op.create_table("payments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("order_id", sa.Integer(), sa.ForeignKey("orders.id", ondelete="CASCADE"), nullable=False), sa.Column("provider", sa.String(32), nullable=False), sa.Column("provider_payment_id", sa.String(128), nullable=False), sa.Column("raw_event_id", sa.String(128)), sa.Column("status", sa.String(32), nullable=False), sa.Column("amount_minor", sa.Integer(), nullable=False), sa.Column("currency", sa.String(8), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False)); op.create_index("uq_payment_provider_id", "payments", ["provider", "provider_payment_id"], unique=True); op.create_index("uq_payment_raw_event", "payments", ["raw_event_id"], unique=True)
    op.create_table("entitlements", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("feature", sa.String(64), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("expires_at", sa.DateTime()), sa.Column("source", sa.String(64), nullable=False)); op.create_index("uq_entitlement_user_feature", "entitlements", ["user_id", "feature"], unique=True)
    op.create_table("ai_usage", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("provider", sa.String(64), nullable=False), sa.Column("model", sa.String(128), nullable=False), sa.Column("input_tokens", sa.Integer(), nullable=False), sa.Column("output_tokens", sa.Integer(), nullable=False), sa.Column("request_id", sa.String(128)), sa.Column("created_at", sa.DateTime(), nullable=False)); op.create_index("ix_ai_usage_user_id", "ai_usage", ["user_id"])
    op.create_table("admin_users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sa.String(320), nullable=False), sa.Column("password_hash", sa.Text(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("is_superadmin", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(), nullable=False)); op.create_index("ix_admin_users_email", "admin_users", ["email"], unique=True)
    op.create_table("system_settings", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("key", sa.String(120), nullable=False), sa.Column("value", sa.Text(), nullable=False), sa.Column("is_secret", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("description", sa.Text(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False)); op.create_index("ix_system_settings_key", "system_settings", ["key"], unique=True)

def downgrade():
    for name in ["system_settings","admin_users","ai_usage","entitlements","payments","orders","products","health_alerts","health_metrics","health_records","memories","users"]: op.drop_table(name)
